ITI.ElectroDev.Presentation/Controllers/BrandController.cs
using ITI.ElectroDev.Models;
using ITI.ElectroDev.Presentation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using System.Xml.Linq;
using X.PagedList;

namespace ITI.ElectroDev.Presentation
{
    [Authorize(Roles ="Admin,Editor")]
    public class BrandController : Controller
    {
        Context dbcontext;
        public BrandController(Context _dbContext)
        {
            dbcontext = _dbContext;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var Brands = dbcontext.Brands.ToList();
            return View(Brands);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            ViewBag.Title = "Brand Details";
            Brand brand = dbcontext.Brands.FirstOrDefault(b => b.Id == id);
            return View(brand);
        }

        [HttpGet]
        public IActionResult AddNewBrand()
        {
            ViewBag.Title = "Add New Brand";
            ViewBag.Categories = dbcontext.Category
                .Select(b => new SelectListItem(b.Name, b.Id.ToString()));
            return View();
        }

        [HttpPost]

        public IActionResult AddNewBrand(BrandModel brand)
        {
            //string image;

            if (ModelState.IsValid == false)
            {
                var errors =
                    ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                    ModelState.AddModelError("", err);
                ViewBag.Success = false;
                return View();
            }
            else
            {
                Brand Brand = new Brand
                {
                    Name = brand.Name,
                    CategoryId = brand.CategoryId
                };
                dbcontext.Brands.Add(Brand);
                dbcontext.SaveChanges();
                ViewBag.Success = true;
                return View();
            }
        }

        
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Brand";
            ViewBag.Categories = dbcontext.Category
                .Select(b => new SelectListItem(b.Name, b.Id.ToString()));
            Brand brand = dbcontext.Brands.FirstOrDefault(i => i.Id == id);
            BrandModel brandModel = new BrandModel
            {
                CategoryId = brand.CategoryId,
                Id = brand.Id,
                Name = brand.Name
            };
            return View(brandModel);
        }
                
        [HttpPost]
        public IActionResult Edit(BrandModel model)
        {
            Brand brand = dbcontext.Brands.FirstOrDefault(i => i.Id == model.Id);
            brand.Name = model.Name;
            brand.CategoryId=model.CategoryId;
            dbcontext.Brands.Update(brand);
            dbcontext.SaveChanges();
            return RedirectToAction("AllBrand"); 
        }

        [HttpGet]
        public IActionResult Delete(Brand brand)
        {
            dbcontext.Brands.Remove(brand);
            dbcontext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ITI.ElectroDev.Presentation/Controllers/CategoryController.cs
using ITI.ElectroDev.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;

namespace ITI.ElectroDev.Presentation
{
    [Authorize(Roles = "Admin,Editor")]

    public class CategoryController : Controller
    {
        private Context db;
        public CategoryController(Context _db)
        {
            db = _db; 
        }
        [HttpGet]
        public IActionResult Index()
        {
            var categories = db.Category.ToList();
            return View(categories);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult Add()
        {
            
            return View();
        }

        [HttpPost]

        public IActionResult Add(CategoryCreateModel model)
        {

            if (ModelState.IsValid == false)
            {
                var errors =
                     ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                    ModelState.AddModelError("", err);

                return View();
            }
            else
            {
                db.Category.Add(new Category { Name = model.Name });
                db.SaveChanges();
                return View();
            }
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult Edit(int id, string name)
        {
            
            dynamic category = new ExpandoObject();
            category.Name = name;
            category.Id = id;
            return View(category);
        }
        [HttpGet]

        public IActionResult SaveEdit(int id,string name)
        {
            var category = db.Category.FirstOrDefault(i => i.Id == id);
            category.Name = name;
            category.Id = id;
            db.Category.Update(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult Delete(int id)
        {
            var category = db.Category.FirstOrDefault(i => i.Id == id);
            db.Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
    }
}

ITI.ElectroDev.Presentation/Controllers/OrderController.cs
using ITI.ElectroDev.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace ITI.ElectroDev.Presentation
{
    [Authorize(Roles = "Admin,Editor")]

    public class OrderController : Controller
    {
        Context context;
        public OrderController(Context _context)
        {
            context = _context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Title = "Orders List";
            List<OrderDetails> orders=context.OrderDetails.ToList();
            return View(orders);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult OrderInfo(int id)
        {
            ViewBag.Title = "Order Information";
            var order = context.OrderDetails.FirstOrDefault(x => x.Id == id);
            return View(order);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult Add()
        {
            ViewBag.Title = "Add New Order";
            ViewBag.Products = context.Product
                .Select(p => new SelectListItem(p.Name, p.Id.ToString()));
            ViewBag.Users = context.Users
                .Select(u => new SelectListItem(u.FirstName + u.LastName, u.Id)); //Id of user is string
            return View();
        }

        [HttpPost]
        public IActionResult Add(OrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Products = context.Product
                .Select(p => new SelectListItem(p.Name, p.Id.ToString()));
                ViewBag.Users = context.Users
                    .Select(u => new SelectListItem(u.FirstName + u.LastName, u.Id)); //Id of user is string
                return View();
            }
            else
            {
                context.OrderDetails.Add(new OrderDetails
                {
                    UserId = model.UserId,
                    Status = model.Status,
                    PaymentMethod = model.Type,
                    TotalPrice = model.TotalPrice
                });
                context.SaveChanges();
                context.OrderItems.Add(new OrderItems
                {
                    ProductId = model.ProductId,
                    //CreatedAt = model.CreatedAt
                });
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Editor")]

        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit";
            ViewBag.Products = context.Product
                .Select(p => new SelectListItem(p.Name, p.Id.ToString()));
            ViewBag.Users = context.Users
                .Select(u => new SelectListItem(u.FirstName + u.LastName, u.Id));
            OrderDetails order = context.OrderDetails.FirstOrDefault(o => o.Id == id);
            OrderViewModel orderModel = new OrderViewModel
            {
                Status = order.Status,
                Type = order.PaymentMethod
            };
            return View(orderModel);
        }
        [HttpPost]
        public IActionResult Edit(OrderViewModel model)
        {
            OrderDetails order = context.OrderDetails.FirstOrDefault(o => o.Id == model.Id);
            order.Status = model.Status;
            order.PaymentMethod = model.Type;
            context.OrderDetails.Update(order);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ITI.ElectroDev.Presentation/Controllers/ProductController.cs
using ITI.ElectroDev.Models;
using ITI.ElectroDev.Presentation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyModel;
using System.Dynamic;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using X.PagedList;

namespace ITI.ElectroDev.Presentation
{

    [Authorize(Roles = "Admin,Editor")]

    public class ProductController : Controller
    {
        private IWebHostEnvironment Environment;

        private Context context;
        IConfiguration con;
        public ProductController(Context _context , IConfiguration _con , IWebHostEnvironment _environment)
        {
            context = _context;
            con = _con;
            Environment = _environment;
        }

        [HttpGet]
        public  IActionResult Index(int PageIndex = 1, int PageSize = 3)
        {
            var product =  context.Product.ToPagedList(PageIndex, PageSize);
            // ViewBag.ImagesPath = con.GetSection("ImagesPath").Value.ToString();
            string wwwPath = this.Environment.WebRootPath;
            ViewBag.contentPath = this.Environment.ContentRootPath;
            return View(product);
        }

        [HttpGet]
        public  IActionResult Create()
        {
            ViewBag.brands = context.Brands.Select(i => new SelectListItem(i.Name, i.Id.ToString()));
            return View();
        }


        [HttpPost]
        public IActionResult Create(ProductCreateModel createModel)
        {

            if (ModelState.IsValid == false)
            {
                var errors =
                    ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                    ModelState.AddModelError("", err);


                ViewBag.brands = context.Brands.Select(i => new SelectListItem(i.Name, i.Id.ToString()));

                return View();
            }
            else
            {
                List<ProductImages> productImages = new List<ProductImages>();
                foreach (IFormFile file in createModel.Images)
                {
                    // Change file Name by Generated Unigue Identifier , because when add in
                    // Images Folder perhaps is Name File The Same Name and This is not good  
                    string newName = Guid.NewGuid().ToString() + file.FileName;
                    productImages.Add(new ProductImages()
                    {
                        Path = newName
                    });


                    // to collect object in Memory
                    FileStream fs = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images", newName), FileMode.OpenOrCreate, FileAccess.ReadWrite);

                    // to Transfer from stream to hard disk
                    file.CopyTo(fs);

                    // To Close Stream 
                    fs.Position = 0;
                }

                context.Product.Add(new Product()
                {
                    Name = createModel.Name,
                    Description = createModel.Description,
                    BrandId = createModel.BrandId,
                    Price = createModel.Price,
                    Discount = createModel.Discount,
                    DiscountPrice=createModel.Price - (createModel.Price * createModel.Discount / 100),
                    Quantity = createModel.Quantity ,
                    ProductImages = productImages,
                });




                context.SaveChanges();

                return RedirectToAction("Index");

            }





        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return BadRequest();

            var prd = await context.Product.FindAsync(id);

                if (prd == null)
                return NotFound();

            var viewModel = new ProductCreateModel
            {
                id = prd.Id,
                Name = prd.Name,
                Description = prd.Description,
                BrandId = prd.BrandId,
                Price = prd.Price,
                Discount = prd.Discount,
                Quantity = prd.Quantity,
                

            };
            ViewBag.brands = context.Brands.Select(i => new SelectListItem(i.Name, i.Id.ToString()));

            return View(viewModel);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(ProductCreateModel model)
        {
            if (ModelState.IsValid == false)
            {
                var errors =
                    ModelState.SelectMany(i => i.Value.Errors.Select(x => x.ErrorMessage));

                foreach (string err in errors)
                    ModelState.AddModelError("", err);


                ViewBag.brands = context.Brands.Select(i => new SelectListItem(i.Name, i.Id.ToString()));

                return View();
            }
            var prd = await context.Product.FindAsync(model.id);

            if (prd == null)
                return NotFound();
            prd.Name = model.Name;
            prd.Description = model.Description;
            prd.Price = model.Price;
            prd.Discount = model.Discount;
            prd.DiscountPrice = model.Price-(model.Price * model.Discount / 100);
            prd.Quantity = model.Quantity;
            prd.BrandId = model.BrandId;

            context.SaveChanges();
            return RedirectToAction("Index");

        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return BadRequest();

            var prd = await context.Product.FindAsync(id);

            if (prd == null)
                return NotFound();

            return View(prd);

        }

        [HttpGet]
        public IActionResult ConfirmDelete(int id, string Name)
        {
            dynamic product = new ExpandoObject();
            product.Name = Name;
            product.ID = id;
            return View(product);
        }


        [HttpGet]
        public IActionResult Delete(int id)
        {
            var product = context.Product.FirstOrDefault(i => i.Id == id);
            context.Product.Remove(product);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Search(string term, int PageIndex = 1, int PageSize = 2)
        {
            var resulte = context.Product.Where(p => p.Name.Contains(term) || p.Description.Contains(term)).ToPagedList(PageIndex, PageSize);
            
            return View("Index" , resulte);
        }


    }
}

ITI.ElectroDev.Presentation/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

ITI.ElectroDev.Presentation/Views/Shared/_Layout.cshtml
@{
	var isRTL = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}

<!DOCTYPE html>
<html lang="en" dir="@(isRTL ? "RTL" : "LTR")">
<head>
	<title>Amazon Admin Dashboard</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	    @Html.Partial("_Favicons")
	<!-- bootstrap-css -->
	<link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
	<!-- Custom CSS -->
	<link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
	<link href="~/Content/css/style-responsive.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://therichpost.com/responsivestyle/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.4.0/font/bootstrap-icons.min.css">
	<!-- font CSS -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
	<!-- font-awesome icons -->
	<link rel="stylesheet" href="~/Content/css/font.css" type="text/css" />
	<link href="~/Content/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" href="~/Content/css/morris.css" type="text/css" />
	<!-- calendar -->
	<link rel="stylesheet" href="~/Content/css/monthly.css">
	<!-- //calendar -->
	@RenderSection("style", false)
	<!-- //font-awesome icons -->
    <link rel="stylesheet" href="~/Content/lib/twitter-bootstrap/css/bootstrap.min.css" />
	<script src="~/Content/js/jquery2.0.3.min.js"></script>
	<script src="~/Content/js/raphael-min.js"></script>
	<script src="~/Content/js/morris.js"></script>
	@if (isRTL)
	{
	 <link href="~/Content/css/StyleSheet.css" rel='stylesheet' type='text/css' />
	 <link href="~/Content/css/style-responsiv-rtl.css" rel='stylesheet' type='text/css' />
     <link rel="stylesheet" href="https://therichpost.com/responsivestyle/index.css">
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.4.0/font/bootstrap-icons.min.css">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

	}

</head>
<body>
	<section id="container">
		<!--header start-->
		<header class="header fixed-top clearfix" style="background-color:black;border:1px solid #fc9b12">
			<!--logo start-->

			<div class="brand" style="background-color:black; color:white ; border:1px solid #fc9b12">
				<a class="logo text-sm fs-6 fw-bold" asp-action="Index" asp-controller="Home">
					Amazon  Dashboard
				</a>
				@*<img class="w-20 mx-auto rounded d-flex" src="~/wwwroot/Images/amazonblack.png">*@

				<div class="sidebar-toggle-box" style="background-color:black;">
					<div class="fa fa-bars"></div>
				</div>
			</div>
			<!--logo end-->
			
			<div class="top-nav clearfix d-flex">
				<!--search & user info start-->
				<ul class="nav top-menu">
					<li>
						<div>
							<partial name="_SelectLanguage" />
						</div>
					</li>
				</ul>
				<form class="container-fluid d-flex" asp-action="Search" asp-controller="Product">
					<input style="background-color:white;border:2px solid #fc9b12;" class="form-control me-2" type="search" name="term" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success me-3" type="submit" style="color:white;background-color:#fc9b12"><i class="bi bi-search"></i></button>
				</form>
				<!--search & user info end-->
			</div>
		</header>
		<!--header end-->
		<!--sidebar start-->
		<aside>
			<div id="sidebar" class="nav-collapse">
				<!-- sidebar menu start-->
				<div class="leftside-navigation" style="background-color:black;border:1px solid #fc9b12">
					<ul class="sidebar-menu" id="nav-accordion">

						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="Index" asp-controller="Category" >
								<i class="fa fa-align-justify"></i>
								<span>@localizer["Categories"]</span>
							</a>
						</li>
						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="Index" asp-controller="Brand">
								<i class="fa fa-dashboard"></i>
								<span>@localizer["Brands"]</span>
							</a>
						</li>
						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="Index" asp-controller="Product">
								<i class="fa fa-dashboard"></i>
								<span>@localizer["Products"]</span>
							</a>
						</li>
						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="Index" asp-controller="Order">
								<i class="fa fa-dashboard"></i>
								<span>@localizer["Orders"]</span>
							</a>
						</li>
						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="UsersDetails" asp-controller="User">
								<i class="bi bi-people-fill"></i>
								<span>@localizer["Users"]</span>
							</a>
						</li>
						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="Index" asp-controller="Home">
								<i class="bi bi-person-circle"></i>
								<span>@localizer["Account"] - @User.Identity.Name</span>
							</a>
						</li>

						<li style="background-color:black;border:1px solid #fc9b12">
							<a class="active" asp-action="SignOut" asp-controller="User">
								<i class="bi bi-box-arrow-left"></i>
								<span>@localizer["Logout"]</span>
							</a>
						</li>
					</ul>
				</div>
				<!-- sidebar menu end-->
			</div>
		</aside>
		<!--sidebar end-->
		
		<!--main content start-->
		<section id="main-content" style="height: 100vh">
			<section class="wrapper">
				<!-- //market-->
				@RenderBody()
			</section>
		
			<!-- / footer -->
		</section>
		<!--main content end-->
	</section>
	<script src="~/Content/js/bootstrap.js"></script>
	<script src="~/Content/js/jquery.dcjqaccordion.2.7.js"></script>
	<script src="~/Content/js/scripts.js"></script>
	<script src="~/Content/js/jquery.slimscroll.js"></script>
	<script src="~/Content/js/jquery.nicescroll.js"></script>
	<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
	<script src="~/Content/js/jquery.scrollTo.js"></script>
	<!-- morris JavaScript -->
	<script>
		$(document).ready(function () {
			//BOX BUTTON SHOW AND CLOSE
			jQuery('.small-graph-box').hover(function () {
				jQuery(this).find('.box-button').fadeIn('fast');
			}, function () {
				jQuery(this).find('.box-button').fadeOut('fast');
			});
			jQuery('.small-graph-box .box-close').click(function () {
				jQuery(this).closest('.small-graph-box').fadeOut(200);
				return false;
			});

			//CHARTS
			function gd(year, day, month) {
				return new Date(year, month - 1, day).getTime();
			}

			graphArea2 = Morris.Area({
				element: 'hero-area',
				padding: 10,
				behaveLikeLine: true,
				gridEnabled: false,
				gridLineColor: '#dddddd',
				axes: true,
				resize: true,
				smooth: true,
				pointSize: 0,
				lineWidth: 0,
				fillOpacity: 0.85,
				data: [
					{ period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649 },
					{ period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051 },
					{ period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910 },
					{ period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695 },
					{ period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300 },
					{ period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891 },
					{ period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598 },
					{ period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185 },
					{ period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038 },

				],
				lineColors: ['#eb6f6f', '#926383', '#eb6f6f'],
				xkey: 'period',
				redraw: true,
				ykeys: ['iphone', 'ipad', 'itouch'],
				labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],
				pointSize: 2,
				hideHover: 'auto',
				resize: true
			});


		});
	</script>
	<!-- calendar -->
	<script type="text/javascript" src="~/Content/js/monthly.js"></script>
	<script type="text/javascript">
		$(window).load(function () {

			$('#mycalendar').monthly({
				mode: 'event',

			});

			$('#mycalendar2').monthly({
				mode: 'picker',
				target: '#mytarget',
				setWidth: '250px',
				startHidden: true,
				showTrigger: '#mytarget',
				stylePast: true,
				disablePast: true
			});

			switch (window.location.protocol) {
				case 'http:':
				case 'https:':
					// running on a server, should be good.
					break;
				case 'file:':
					alert('Just a heads-up, events will not work when run locally.');
			}

		});
	</script>
	<!-- //calendar -->
	<!-- jQuery Plugins -->
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ITI.ElectroDev.Presentation/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Http.Features;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Options;

@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = options.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "/" : $"{Context.Request.Path.Value}";
}

<div>
    <form method="post" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl">
        <select class="form-select" name="culture"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
            asp-items="cultures"
            onchange="this.form.submit();"
        >
        </select>
    </form>
</div>